language: node_js
node_js:
  - 4.0
before_install:
  - npm install -g grunt-cli
install:
  - npm install
script:
  # Reference the locally-installed version of Grunt
  - ./node_modules/grunt-cli/bin/grunt test
after_success:
  # Check to see if the version file has been updated
  - ./create-release-tag.sh

notifications:
  email: false

sudo: false
